name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  RunMake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential dpkg-dev

      - name: Run Make
        run: |
          cd src
          make || { echo "Make failed"; exit 1; }
          ls -l
          mkdir -p ../artifacts
          cp main ../artifacts/ || { echo "Failed to copy main to artifacts"; exit 1; }

      - name: Upload Artifact (Binary)
        uses: actions/upload-artifact@v4
        with:
          name: main-binary
          path: artifacts/

  RunTest:
    needs: RunMake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: main-binary
          path: artifacts/

      - name: Run Tests
        run: |
          chmod +x artifacts/main
          echo "Run with argument 3"
          ./artifacts/main 3
          echo "Run with argument 5"
          ./artifacts/main 5
          echo "Run with argument 6"
          ./artifacts/main 6

  RunPackage:
    needs: RunTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: main-binary
          path: artifacts/

      - name: Create Debian Package
        run: |
          mkdir -p artifacts/deb/usr/local/bin
          mkdir -p artifacts/deb/DEBIAN
          cp DEBIAN/control artifacts/deb/DEBIAN
          cp artifacts/main artifacts/deb/usr/local/bin
          dpkg-deb --build artifacts/deb lab2.deb

      - name: Upload Debian Package
        uses: actions/upload-artifact@v4
        with:
          name: lab2-deb
          path: lab2.deb

  RunDeploy:
    needs: RunPackage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Debian Package
        uses: actions/download-artifact@v4
        with:
          name: lab2-deb
          path: ./  

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: |
              docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/lab1:latest .

      - name: Run Docker container
        timeout-minutes: 3
        run: docker run -i --rm ${{ secrets.DOCKER_HUB_USERNAME }}/lab1:latest 10
        
      - name: Push Docker image
        run: |
              docker push ${{ secrets.DOCKER_HUBDOCKER_HUB_USERNAME_USER }}/lab1:latest
